# Configurações de conexão com o SQLServer
bancos:
    server: 'ANANDA_AN\ANASCIMESERVER'
    database: 'ENEL_GEO_SIGR_PERDAS19'
    username: 'usr_GeoPerdas'
    password: '123456'
    schema: 'SDE'

tipo_arquivo: "gdb"    #: [gbd ou dbf]

data_base: "2019-12-31"
dist: '390'
cod_BDGD: '0907'

dbf_directory: 'E:\Ananda\Documents\Enerq\02_dbf_sql\shape_enel_2019'

gdb_directory: 'E:\Ananda\Documents\Enerq\gdbs\ENEL_SP_390_2019-12-31_M10_20201222-0907.gdb'
gdb_file: 'ENEL_SP_390_2019-12-31_M10_20201222-0907.gdb'